{
 "title": "Gateway2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Quality",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"quality\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"performance\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"availability\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "OEE",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"oee\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "SELECT * FROM \"production1\""
    }
   ]
  },
  {
   "title": "Measurement",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "query": "SELECT * FROM \"production1\""
    }
   ]
  },
  {
   "title": "Alarm Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "query": "SELECT * FROM \"production1\""
    }
   ]
  },
  {
   "title": "Store",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT store FROM \"production1\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "query": "SELECT * FROM \"production1\""
    }
   ]
  },
  {
   "title": "OK",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"production1\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NG",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT ng FROM \"production1\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "production1",
     "query": "SELECT * FROM \"production2\"",
     "select": [
      [
       { "params": [ "measurement" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}